# 2. DataFrame

2차원 데이터 (Series들의 모음)

## Data 준비

사전 (dict) 자료구조를 토앻 생성

예) 2022/23시즌 아스날 FC의 베스트 일레븐 11명에 대한 데이터

In [1]:
data = {
    '이름' : ['가브리엘 제수스', '가브리엘 마르티넬리', '부카요 사카', '그라니트 자카', '마르틴 외데고르', '토마스 파티', '올렉산드르 진첸코', '가브리엘 마갈량이스', '윌리엄 살리바', '벤 화이트', '아론 람스데일'],
    '포지션' : ['FW', 'FW', 'FW', 'MF', 'MF', 'MF', 'DF', 'DF', 'DF', 'DF', 'GK'],
    '국적' : ['브라질', '브라질', '잉글랜드', '스위스', '노르웨이', '가나', '우크라이나', '브라질', '프랑스', '잉글랜드', '잉글랜드'],
    '등번호' : [9, 11, 7, 34, 8, 5, 35, 6, 12, 4, 1],
    '키' : [175, 180, 178, 185, 176, 185, 175, 190, 193, 182, 188],
    '출생년도' : [1997, 2001, 2001, 1992, 1998, 1993, 1996, 1997, 2001, 1997, 1998]
}
data

{'이름': ['가브리엘 제수스',
  '가브리엘 마르티넬리',
  '부카요 사카',
  '그라니트 자카',
  '마르틴 외데고르',
  '토마스 파티',
  '올렉산드르 진첸코',
  '가브리엘 마갈량이스',
  '윌리엄 살리바',
  '벤 화이트',
  '아론 람스데일'],
 '포지션': ['FW', 'FW', 'FW', 'MF', 'MF', 'MF', 'DF', 'DF', 'DF', 'DF', 'GK'],
 '국적': ['브라질',
  '브라질',
  '잉글랜드',
  '스위스',
  '노르웨이',
  '가나',
  '우크라이나',
  '브라질',
  '프랑스',
  '잉글랜드',
  '잉글랜드'],
 '등번호': [9, 11, 7, 34, 8, 5, 35, 6, 12, 4, 1],
 '키': [175, 180, 178, 185, 176, 185, 175, 190, 193, 182, 188],
 '출생년도': [1997, 2001, 2001, 1992, 1998, 1993, 1996, 1997, 2001, 1997, 1998]}

In [2]:
data['이름']

['가브리엘 제수스',
 '가브리엘 마르티넬리',
 '부카요 사카',
 '그라니트 자카',
 '마르틴 외데고르',
 '토마스 파티',
 '올렉산드르 진첸코',
 '가브리엘 마갈량이스',
 '윌리엄 살리바',
 '벤 화이트',
 '아론 람스데일']

In [3]:
data['키']

[175, 180, 178, 185, 176, 185, 175, 190, 193, 182, 188]

## DataFrame 객체 생성

In [4]:
import pandas as pd
df = pd.DataFrame(data)

In [5]:
df

            이름 포지션     국적  등번호    키  출생년도
0     가브리엘 제수스  FW    브라질    9  175  1997
1   가브리엘 마르티넬리  FW    브라질   11  180  2001
2       부카요 사카  FW   잉글랜드    7  178  2001
3      그라니트 자카  MF    스위스   34  185  1992
4     마르틴 외데고르  MF   노르웨이    8  176  1998
5       토마스 파티  MF     가나    5  185  1993
6    올렉산드르 진첸코  DF  우크라이나   35  175  1996
7   가브리엘 마갈량이스  DF    브라질    6  190  1997
8      윌리엄 살리바  DF    프랑스   12  193  2001
9        벤 화이트  DF   잉글랜드    4  182  1997
10     아론 람스데일  GK   잉글랜드    1  188  1998

## 데이터 접근

In [6]:
df['이름']

0       가브리엘 제수스
1     가브리엘 마르티넬리
2         부카요 사카
3        그라니트 자카
4       마르틴 외데고르
5         토마스 파티
6      올렉산드르 진첸코
7     가브리엘 마갈량이스
8        윌리엄 살리바
9          벤 화이트
10       아론 람스데일
Name: 이름, dtype: object

In [7]:
df['키']

0     175
1     180
2     178
3     185
4     176
5     185
6     175
7     190
8     193
9     182
10    188
Name: 키, dtype: int64

In [8]:
df[['이름', '포지션']]

            이름 포지션
0     가브리엘 제수스  FW
1   가브리엘 마르티넬리  FW
2       부카요 사카  FW
3      그라니트 자카  MF
4     마르틴 외데고르  MF
5       토마스 파티  MF
6    올렉산드르 진첸코  DF
7   가브리엘 마갈량이스  DF
8      윌리엄 살리바  DF
9        벤 화이트  DF
10     아론 람스데일  GK

## DataFrame 객체 생성 (Index 지정)

In [10]:
df = pd.DataFrame(data, index = [1,2,3,4,5,6,7,8,9,10,11]) # 데이터의 개수와 꼭 맞춰서 지정해야 함
df

            이름 포지션     국적  등번호    키  출생년도
1     가브리엘 제수스  FW    브라질    9  175  1997
2   가브리엘 마르티넬리  FW    브라질   11  180  2001
3       부카요 사카  FW   잉글랜드    7  178  2001
4      그라니트 자카  MF    스위스   34  185  1992
5     마르틴 외데고르  MF   노르웨이    8  176  1998
6       토마스 파티  MF     가나    5  185  1993
7    올렉산드르 진첸코  DF  우크라이나   35  175  1996
8   가브리엘 마갈량이스  DF    브라질    6  190  1997
9      윌리엄 살리바  DF    프랑스   12  193  2001
10       벤 화이트  DF   잉글랜드    4  182  1997
11     아론 람스데일  GK   잉글랜드    1  188  1998

## DataFrame 객체 생성 (Column 지정)

data 중에서 원하는 column만 선택하거나, 순서 변경 가능

In [12]:
df = pd.DataFrame(data, columns = ['포지션', '이름', '국적'])
df

   포지션          이름     국적
0   FW    가브리엘 제수스    브라질
1   FW  가브리엘 마르티넬리    브라질
2   FW      부카요 사카   잉글랜드
3   MF     그라니트 자카    스위스
4   MF    마르틴 외데고르   노르웨이
5   MF      토마스 파티     가나
6   DF   올렉산드르 진첸코  우크라이나
7   DF  가브리엘 마갈량이스    브라질
8   DF     윌리엄 살리바    프랑스
9   DF       벤 화이트   잉글랜드
10  GK     아론 람스데일   잉글랜드