# 3. Index

데이터에 접근할 수 있는 주소 값

In [1]:
import  pandas as pd
data = {
    '이름' : ['가브리엘 제수스', '가브리엘 마르티넬리', '부카요 사카', '그라니트 자카', '마르틴 외데고르', '토마스 파티', '올렉산드르 진첸코', '가브리엘 마갈량이스', '윌리엄 살리바', '벤 화이트', '아론 람스데일'],
    '포지션' : ['FW', 'FW', 'FW', 'MF', 'MF', 'MF', 'DF', 'DF', 'DF', 'DF', 'GK'],
    '국적' : ['브라질', '브라질', '잉글랜드', '스위스', '노르웨이', '가나', '우크라이나', '브라질', '프랑스', '잉글랜드', '잉글랜드'],
    '등번호' : [9, 11, 7, 34, 8, 5, 35, 6, 12, 4, 1],
    '키' : [175, 180, 178, 185, 176, 185, 175, 190, 193, 182, 188],
    '출생년도' : [1997, 2001, 2001, 1992, 1998, 1993, 1996, 1997, 2001, 1997, 1998]
}
df = pd.DataFrame(data, index = [1,2,3,4,5,6,7,8,9,10,11])
df

            이름 포지션     국적  등번호    키  출생년도
1     가브리엘 제수스  FW    브라질    9  175  1997
2   가브리엘 마르티넬리  FW    브라질   11  180  2001
3       부카요 사카  FW   잉글랜드    7  178  2001
4      그라니트 자카  MF    스위스   34  185  1992
5     마르틴 외데고르  MF   노르웨이    8  176  1998
6       토마스 파티  MF     가나    5  185  1993
7    올렉산드르 진첸코  DF  우크라이나   35  175  1996
8   가브리엘 마갈량이스  DF    브라질    6  190  1997
9      윌리엄 살리바  DF    프랑스   12  193  2001
10       벤 화이트  DF   잉글랜드    4  182  1997
11     아론 람스데일  GK   잉글랜드    1  188  1998

In [2]:
df.index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64')

## Index 이름 설정

In [3]:
df.index.name = '순서'
df

            이름 포지션     국적  등번호    키  출생년도
순서
1     가브리엘 제수스  FW    브라질    9  175  1997
2   가브리엘 마르티넬리  FW    브라질   11  180  2001
3       부카요 사카  FW   잉글랜드    7  178  2001
4      그라니트 자카  MF    스위스   34  185  1992
5     마르틴 외데고르  MF   노르웨이    8  176  1998
6       토마스 파티  MF     가나    5  185  1993
7    올렉산드르 진첸코  DF  우크라이나   35  175  1996
8   가브리엘 마갈량이스  DF    브라질    6  190  1997
9      윌리엄 살리바  DF    프랑스   12  193  2001
10       벤 화이트  DF   잉글랜드    4  182  1997
11     아론 람스데일  GK   잉글랜드    1  188  1998

## Index 초기화

In [4]:
df.reset_index() # 기존의 Index는 하나의 Column이 됨

    순서          이름 포지션     국적  등번호    키  출생년도
0    1    가브리엘 제수스  FW    브라질    9  175  1997
1    2  가브리엘 마르티넬리  FW    브라질   11  180  2001
2    3      부카요 사카  FW   잉글랜드    7  178  2001
3    4     그라니트 자카  MF    스위스   34  185  1992
4    5    마르틴 외데고르  MF   노르웨이    8  176  1998
5    6      토마스 파티  MF     가나    5  185  1993
6    7   올렉산드르 진첸코  DF  우크라이나   35  175  1996
7    8  가브리엘 마갈량이스  DF    브라질    6  190  1997
8    9     윌리엄 살리바  DF    프랑스   12  193  2001
9   10       벤 화이트  DF   잉글랜드    4  182  1997
10  11     아론 람스데일  GK   잉글랜드    1  188  1998

In [5]:
df.reset_index(drop=True) # 원래 쓰던 Index 삭제 (실제 데이터에 반영 X)

            이름 포지션     국적  등번호    키  출생년도
0     가브리엘 제수스  FW    브라질    9  175  1997
1   가브리엘 마르티넬리  FW    브라질   11  180  2001
2       부카요 사카  FW   잉글랜드    7  178  2001
3      그라니트 자카  MF    스위스   34  185  1992
4     마르틴 외데고르  MF   노르웨이    8  176  1998
5       토마스 파티  MF     가나    5  185  1993
6    올렉산드르 진첸코  DF  우크라이나   35  175  1996
7   가브리엘 마갈량이스  DF    브라질    6  190  1997
8      윌리엄 살리바  DF    프랑스   12  193  2001
9        벤 화이트  DF   잉글랜드    4  182  1997
10     아론 람스데일  GK   잉글랜드    1  188  1998

In [6]:
df

            이름 포지션     국적  등번호    키  출생년도
순서
1     가브리엘 제수스  FW    브라질    9  175  1997
2   가브리엘 마르티넬리  FW    브라질   11  180  2001
3       부카요 사카  FW   잉글랜드    7  178  2001
4      그라니트 자카  MF    스위스   34  185  1992
5     마르틴 외데고르  MF   노르웨이    8  176  1998
6       토마스 파티  MF     가나    5  185  1993
7    올렉산드르 진첸코  DF  우크라이나   35  175  1996
8   가브리엘 마갈량이스  DF    브라질    6  190  1997
9      윌리엄 살리바  DF    프랑스   12  193  2001
10       벤 화이트  DF   잉글랜드    4  182  1997
11     아론 람스데일  GK   잉글랜드    1  188  1998

In [7]:
df.reset_index(drop=True, inplace=True) # 실제 데이터에 바로 반영

In [8]:
df

            이름 포지션     국적  등번호    키  출생년도
0     가브리엘 제수스  FW    브라질    9  175  1997
1   가브리엘 마르티넬리  FW    브라질   11  180  2001
2       부카요 사카  FW   잉글랜드    7  178  2001
3      그라니트 자카  MF    스위스   34  185  1992
4     마르틴 외데고르  MF   노르웨이    8  176  1998
5       토마스 파티  MF     가나    5  185  1993
6    올렉산드르 진첸코  DF  우크라이나   35  175  1996
7   가브리엘 마갈량이스  DF    브라질    6  190  1997
8      윌리엄 살리바  DF    프랑스   12  193  2001
9        벤 화이트  DF   잉글랜드    4  182  1997
10     아론 람스데일  GK   잉글랜드    1  188  1998

## Index 설정

지정한 column으로 Index를 설정

In [9]:
df.set_index('등번호') # 실제 데이터에 반영 X

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [10]:
df

            이름 포지션     국적  등번호    키  출생년도
0     가브리엘 제수스  FW    브라질    9  175  1997
1   가브리엘 마르티넬리  FW    브라질   11  180  2001
2       부카요 사카  FW   잉글랜드    7  178  2001
3      그라니트 자카  MF    스위스   34  185  1992
4     마르틴 외데고르  MF   노르웨이    8  176  1998
5       토마스 파티  MF     가나    5  185  1993
6    올렉산드르 진첸코  DF  우크라이나   35  175  1996
7   가브리엘 마갈량이스  DF    브라질    6  190  1997
8      윌리엄 살리바  DF    프랑스   12  193  2001
9        벤 화이트  DF   잉글랜드    4  182  1997
10     아론 람스데일  GK   잉글랜드    1  188  1998

In [11]:
df.set_index('등번호', inplace=True)

In [12]:
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

## Index 정렬

Index를 기준으로 오름차순, 내림차순 정렬

In [13]:
df.sort_index() # 인덱스를 오름차순으로 정렬

             이름 포지션     국적    키  출생년도
등번호
1       아론 람스데일  GK   잉글랜드  188  1998
4         벤 화이트  DF   잉글랜드  182  1997
5        토마스 파티  MF     가나  185  1993
6    가브리엘 마갈량이스  DF    브라질  190  1997
7        부카요 사카  FW   잉글랜드  178  2001
8      마르틴 외데고르  MF   노르웨이  176  1998
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
12      윌리엄 살리바  DF    프랑스  193  2001
34      그라니트 자카  MF    스위스  185  1992
35    올렉산드르 진첸코  DF  우크라이나  175  1996

In [14]:
df.sort_index(ascending=False) # 내림차순으로 정렬

             이름 포지션     국적    키  출생년도
등번호
35    올렉산드르 진첸코  DF  우크라이나  175  1996
34      그라니트 자카  MF    스위스  185  1992
12      윌리엄 살리바  DF    프랑스  193  2001
11   가브리엘 마르티넬리  FW    브라질  180  2001
9      가브리엘 제수스  FW    브라질  175  1997
8      마르틴 외데고르  MF   노르웨이  176  1998
7        부카요 사카  FW   잉글랜드  178  2001
6    가브리엘 마갈량이스  DF    브라질  190  1997
5        토마스 파티  MF     가나  185  1993
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998