# 4. 파일 저장 및 열기

DataFrame 객체를 excel, csv, txt 등 형태의 파일로 만들기

In [1]:
import pandas as pd
data = {
    '이름' : ['가브리엘 제수스', '가브리엘 마르티넬리', '부카요 사카', '그라니트 자카', '마르틴 외데고르', '토마스 파티', '올렉산드르 진첸코', '가브리엘 마갈량이스', '윌리엄 살리바', '벤 화이트', '아론 람스데일'],
    '포지션' : ['FW', 'FW', 'FW', 'MF', 'MF', 'MF', 'DF', 'DF', 'DF', 'DF', 'GK'],
    '국적' : ['브라질', '브라질', '잉글랜드', '스위스', '노르웨이', '가나', '우크라이나', '브라질', '프랑스', '잉글랜드', '잉글랜드'],
    '등번호' : [9, 11, 7, 34, 8, 5, 35, 6, 12, 4, 1],
    '키' : [175, 180, 178, 185, 176, 185, 175, 190, 193, 182, 188],
    '출생년도' : [1997, 2001, 2001, 1992, 1998, 1993, 1996, 1997, 2001, 1997, 1998]
}
df = pd.DataFrame(data)
df.set_index('등번호', inplace=True)
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

## 저장하기
### csv 파일로 저장

In [2]:
df.to_csv('04_ARS.csv', encoding='utf-8-sig')

In [3]:
df.to_csv('04_ARS.csv', encoding='utf-8-sig', index=False) # Index 제외하고 저장

### 텍스트(.txt) 파일로 저장

In [4]:
df.to_csv('04_ARS.txt', sep='\t') # to_csv 함수를 사용하고, 확장자를 .txt로 해줌

### 엑셀 파일로 저장

In [5]:
df.to_excel('04_ARS.xlsx')

***
## 열기

### csv 파일 열기

In [6]:
df = pd.read_csv('04_ARS.csv')
df

            이름 포지션     국적    키  출생년도
0     가브리엘 제수스  FW    브라질  175  1997
1   가브리엘 마르티넬리  FW    브라질  180  2001
2       부카요 사카  FW   잉글랜드  178  2001
3      그라니트 자카  MF    스위스  185  1992
4     마르틴 외데고르  MF   노르웨이  176  1998
5       토마스 파티  MF     가나  185  1993
6    올렉산드르 진첸코  DF  우크라이나  175  1996
7   가브리엘 마갈량이스  DF    브라질  190  1997
8      윌리엄 살리바  DF    프랑스  193  2001
9        벤 화이트  DF   잉글랜드  182  1997
10     아론 람스데일  GK   잉글랜드  188  1998

In [8]:
df = pd.read_csv('04_ARS.csv', skiprows=1) # 가장 위 1개의 줄 무시
df

     가브리엘 제수스  FW    브라질  175  1997
0  가브리엘 마르티넬리  FW    브라질  180  2001
1      부카요 사카  FW   잉글랜드  178  2001
2     그라니트 자카  MF    스위스  185  1992
3    마르틴 외데고르  MF   노르웨이  176  1998
4      토마스 파티  MF     가나  185  1993
5   올렉산드르 진첸코  DF  우크라이나  175  1996
6  가브리엘 마갈량이스  DF    브라질  190  1997
7     윌리엄 살리바  DF    프랑스  193  2001
8       벤 화이트  DF   잉글랜드  182  1997
9     아론 람스데일  GK   잉글랜드  188  1998

In [9]:
df = pd.read_csv('04_ARS.csv', skiprows=[1,3,5]) # 1,3,5번째 row는 제외 (0부터 시작)
df

           이름 포지션     국적    키  출생년도
0  가브리엘 마르티넬리  FW    브라질  180  2001
1     그라니트 자카  MF    스위스  185  1992
2      토마스 파티  MF     가나  185  1993
3   올렉산드르 진첸코  DF  우크라이나  175  1996
4  가브리엘 마갈량이스  DF    브라질  190  1997
5     윌리엄 살리바  DF    프랑스  193  2001
6       벤 화이트  DF   잉글랜드  182  1997
7     아론 람스데일  GK   잉글랜드  188  1998

In [10]:
df = pd.read_csv('04_ARS.csv', nrows=4) # 지정된 개수만큼의 row만 가져옴
df

           이름 포지션    국적    키  출생년도
0    가브리엘 제수스  FW   브라질  175  1997
1  가브리엘 마르티넬리  FW   브라질  180  2001
2      부카요 사카  FW  잉글랜드  178  2001
3     그라니트 자카  MF   스위스  185  1992

In [11]:
df = pd.read_csv('04_ARS.csv', skiprows=2, nrows=4) # 처음 2 row 무시하고, 이후 4 row를 가져옴
df

  가브리엘 마르티넬리  FW   브라질  180  2001
0     부카요 사카  FW  잉글랜드  178  2001
1    그라니트 자카  MF   스위스  185  1992
2   마르틴 외데고르  MF  노르웨이  176  1998
3     토마스 파티  MF    가나  185  1993

### 텍스트(.txt) 파일 열기

In [14]:
df = pd.read_csv('04_ARS.txt', sep='\t') # tab을 구분자로 설정하고 가져옴
df

    등번호          이름 포지션     국적    키  출생년도
0     9    가브리엘 제수스  FW    브라질  175  1997
1    11  가브리엘 마르티넬리  FW    브라질  180  2001
2     7      부카요 사카  FW   잉글랜드  178  2001
3    34     그라니트 자카  MF    스위스  185  1992
4     8    마르틴 외데고르  MF   노르웨이  176  1998
5     5      토마스 파티  MF     가나  185  1993
6    35   올렉산드르 진첸코  DF  우크라이나  175  1996
7     6  가브리엘 마갈량이스  DF    브라질  190  1997
8    12     윌리엄 살리바  DF    프랑스  193  2001
9     4       벤 화이트  DF   잉글랜드  182  1997
10    1     아론 람스데일  GK   잉글랜드  188  1998

In [16]:
df = pd.read_csv('04_ARS.txt', sep='\t', index_col='등번호') # index를 지정하여 가져옴
"""
아래도 같은 결과
df = pd.read_csv('04_ARS.txt', sep='\t')
df.set_index('등번호', inplace=True)
"""
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

### 엑셀 파일 열기

In [18]:
df = pd.read_excel('04_ARS.xlsx')
df

    등번호          이름 포지션     국적    키  출생년도
0     9    가브리엘 제수스  FW    브라질  175  1997
1    11  가브리엘 마르티넬리  FW    브라질  180  2001
2     7      부카요 사카  FW   잉글랜드  178  2001
3    34     그라니트 자카  MF    스위스  185  1992
4     8    마르틴 외데고르  MF   노르웨이  176  1998
5     5      토마스 파티  MF     가나  185  1993
6    35   올렉산드르 진첸코  DF  우크라이나  175  1996
7     6  가브리엘 마갈량이스  DF    브라질  190  1997
8    12     윌리엄 살리바  DF    프랑스  193  2001
9     4       벤 화이트  DF   잉글랜드  182  1997
10    1     아론 람스데일  GK   잉글랜드  188  1998

In [19]:
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998