# 5. 데이터 확인

In [1]:
import pandas as pd
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

## DataFrame 확인

계산 가능한 데이터에 대해 Column 별로 데이터의 갯수, 평균, 표준편차, 최소/최대값 등의 정보를 보여줌

In [3]:
df.describe()

                키         출생년도
count   11.000000    11.000000
mean   182.454545  1997.363636
std      6.250818     3.009077
min    175.000000  1992.000000
25%    177.000000  1996.500000
50%    182.000000  1997.000000
75%    186.500000  1999.500000
max    193.000000  2001.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 9 to 1
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      11 non-null     object
 1   포지션     11 non-null     object
 2   국적      11 non-null     object
 3   키       11 non-null     int64
 4   출생년도    11 non-null     int64
dtypes: int64(2), object(3)
memory usage: 528.0+ bytes

In [5]:
df.head() # 처음 5개(default)의 row를 가져옴

             이름 포지션    국적    키  출생년도
등번호
9      가브리엘 제수스  FW   브라질  175  1997
11   가브리엘 마르티넬리  FW   브라질  180  2001
7        부카요 사카  FW  잉글랜드  178  2001
34      그라니트 자카  MF   스위스  185  1992
8      마르틴 외데고르  MF  노르웨이  176  1998

In [6]:
df.head(7) #  처음 7개의 row를 가져옴

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996

In [8]:
df.tail() # 마지막 5개의 row를 가져옴

             이름 포지션     국적    키  출생년도
등번호
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [9]:
df.tail(3) # 마지막 3개의 row를 가져옴

          이름 포지션    국적    키  출생년도
등번호
12   윌리엄 살리바  DF   프랑스  193  2001
4      벤 화이트  DF  잉글랜드  182  1997
1    아론 람스데일  GK  잉글랜드  188  1998

In [10]:
df.values

array([['가브리엘 제수스', 'FW', '브라질', 175, 1997],
       ['가브리엘 마르티넬리', 'FW', '브라질', 180, 2001],
       ['부카요 사카', 'FW', '잉글랜드', 178, 2001],
       ['그라니트 자카', 'MF', '스위스', 185, 1992],
       ['마르틴 외데고르', 'MF', '노르웨이', 176, 1998],
       ['토마스 파티', 'MF', '가나', 185, 1993],
       ['올렉산드르 진첸코', 'DF', '우크라이나', 175, 1996],
       ['가브리엘 마갈량이스', 'DF', '브라질', 190, 1997],
       ['윌리엄 살리바', 'DF', '프랑스', 193, 2001],
       ['벤 화이트', 'DF', '잉글랜드', 182, 1997],
       ['아론 람스데일', 'GK', '잉글랜드', 188, 1998]], dtype=object)

In [11]:
df.index

Int64Index([9, 11, 7, 34, 8, 5, 35, 6, 12, 4, 1], dtype='int64', name='등번호')

In [12]:
df.columns

Index(['이름', '포지션', '국적', '키', '출생년도'], dtype='object')

In [15]:
df.shape # row, column(index 제외)의 갯수

(11, 5)

## Series 확인

In [19]:
df['키'] # column '키'에 해당하는 Series

등번호
9     175
11    180
7     178
34    185
8     176
5     185
35    175
6     190
12    193
4     182
1     188
Name: 키, dtype: int64

In [20]:
df['키'].describe()

count     11.000000
mean     182.454545
std        6.250818
min      175.000000
25%      177.000000
50%      182.000000
75%      186.500000
max      193.000000
Name: 키, dtype: float64

In [21]:
df['키'].min()

175

In [23]:
df['키'].max()

193

In [24]:
df['키'].nlargest(3) # 키가 큰 순서대로 3명의 데이터

등번호
12    193
6     190
1     188
Name: 키, dtype: int64

In [25]:
df['키'].mean() # 평균

182.45454545454547

In [26]:
df['키'].sum() # 총합

2007

In [28]:
df['이름'].count() # 유효한 데이터 값의 갯수 (Null은 count되지 않음)

11

In [32]:
df['국적'].unique() # 중복 제외

array(['브라질', '잉글랜드', '스위스', '노르웨이', '가나', '우크라이나', '프랑스'], dtype=object)

In [33]:
df['국적'].nunique() # 중복을 제외한 결과의 수

7