# 6. 데이터 선택 (기본)

In [1]:
import pandas as pd
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

## Column 선택 (label)

In [3]:
df['이름']

등번호
9       가브리엘 제수스
11    가브리엘 마르티넬리
7         부카요 사카
34       그라니트 자카
8       마르틴 외데고르
5         토마스 파티
35     올렉산드르 진첸코
6     가브리엘 마갈량이스
12       윌리엄 살리바
4          벤 화이트
1        아론 람스데일
Name: 이름, dtype: object

In [4]:
df['키']

등번호
9     175
11    180
7     178
34    185
8     176
5     185
35    175
6     190
12    193
4     182
1     188
Name: 키, dtype: int64

In [5]:
df[['이름','포지션']]

             이름 포지션
등번호
9      가브리엘 제수스  FW
11   가브리엘 마르티넬리  FW
7        부카요 사카  FW
34      그라니트 자카  MF
8      마르틴 외데고르  MF
5        토마스 파티  MF
35    올렉산드르 진첸코  DF
6    가브리엘 마갈량이스  DF
12      윌리엄 살리바  DF
4         벤 화이트  DF
1       아론 람스데일  GK

## Column 선택 (정수 index)

In [6]:
df.columns

Index(['이름', '포지션', '국적', '키', '출생년도'], dtype='object')

In [7]:
df.columns[0]

'이름'

In [8]:
df.columns[2]

'국적'

In [10]:
df[df.columns[0]] # df['이름']과 같은 결과

등번호
9       가브리엘 제수스
11    가브리엘 마르티넬리
7         부카요 사카
34       그라니트 자카
8       마르틴 외데고르
5         토마스 파티
35     올렉산드르 진첸코
6     가브리엘 마갈량이스
12       윌리엄 살리바
4          벤 화이트
1        아론 람스데일
Name: 이름, dtype: object

In [12]:
df[df.columns[-1]] # 우측 맨 끝에 있는 값을 가져옴

등번호
9     1997
11    2001
7     2001
34    1992
8     1998
5     1993
35    1996
6     1997
12    2001
4     1997
1     1998
Name: 출생년도, dtype: int64

## 슬라이싱

In [14]:
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [15]:
df['국적'][0:5] # 0에서 4까지의 국적 데이터 가져옴

등번호
9      브라질
11     브라질
7     잉글랜드
34     스위스
8     노르웨이
Name: 국적, dtype: object

In [16]:
df[['이름', '키']][:3] # 처음 3명의 이름, 키 정보를 가져옴

             이름    키
등번호
9      가브리엘 제수스  175
11   가브리엘 마르티넬리  180
7        부카요 사카  178

In [17]:
df[3:] # 4번째 데이터 부터 전부 가져옴

             이름 포지션     국적    키  출생년도
등번호
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998