# 7. 데이터 선택 (loc)

이름을 이용하여 원하는 row에서 원하는 col 선택

In [2]:
import pandas as pd
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [5]:
df.loc[9] # index 9에 해당하는 전체 데이터

이름      가브리엘 제수스
포지션           FW
국적           브라질
키            175
출생년도        1997
Name: 9, dtype: object

In [7]:
df.loc[12] # index 12에 해당하는 전체 데이터

이름      윌리엄 살리바
포지션          DF
국적          프랑스
키           193
출생년도       2001
Name: 12, dtype: object

In [8]:
df.loc[12,'이름'] # index 12에 해당하는 '이름' 데이터

'윌리엄 살리바'

In [9]:
df.loc[[11,7], '출생년도'] # index 11, 7에 해당하는 '출생년도' 데이터

등번호
11    2001
7     2001
Name: 출생년도, dtype: int64

In [10]:
df.loc[[11, 7], ['이름', '국적']] # index 11, 7에 해당하는 '이름', '국적' 데이터

             이름    국적
등번호
11   가브리엘 마르티넬리   브라질
7        부카요 사카  잉글랜드

In [12]:
df.loc[35:4, '이름':'국적'] # index 35부터 4까지, '이름'부터 '국적'까지의 데이터 (뒷부분 포함)

             이름 포지션     국적
등번호
35    올렉산드르 진첸코  DF  우크라이나
6    가브리엘 마갈량이스  DF    브라질
12      윌리엄 살리바  DF    프랑스
4         벤 화이트  DF   잉글랜드