# 8. 데이터 선택 (iloc)

위치를 이용하여 원하는 row에서 원하는 col 선택

In [1]:
import pandas as pd
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [2]:
df.iloc[0] # 0번째 index에 해당하는 데이터

이름      가브리엘 제수스
포지션           FW
국적           브라질
키            175
출생년도        1997
Name: 9, dtype: object

In [3]:
df.iloc[4] # 4번째 index에 해당하는 데이터

이름      마르틴 외데고르
포지션           MF
국적          노르웨이
키            176
출생년도        1998
Name: 8, dtype: object

In [4]:
df.iloc[0:5] # 0 ~ 4번째 index에 해당하는 데이터

             이름 포지션    국적    키  출생년도
등번호
9      가브리엘 제수스  FW   브라질  175  1997
11   가브리엘 마르티넬리  FW   브라질  180  2001
7        부카요 사카  FW  잉글랜드  178  2001
34      그라니트 자카  MF   스위스  185  1992
8      마르틴 외데고르  MF  노르웨이  176  1998

In [7]:
df.iloc[3, 2] # 3번째 index의 2번째(0부터 시작) 데이터(국적)

'스위스'

In [9]:
df.iloc[7, 4] # 7번째 index의 4번째 데이터 (출생년도)

1997

In [11]:
df.iloc[[0, 1], 0] # 0 ~ 1번째 index의 0번째 데이터(이름)

등번호
9       가브리엘 제수스
11    가브리엘 마르티넬리
Name: 이름, dtype: object

In [12]:
df.iloc[[7, 8], [0, 2, 3]] # 7, 8번째 index의 0, 2, 3번째 데이터(이름, 국적, 키)

             이름   국적    키
등번호
6    가브리엘 마갈량이스  브라질  190
12      윌리엄 살리바  프랑스  193

In [14]:
df.iloc[3:6, 0:3] # 3 ~ 5번째 index의 0 ~ 2번째 데이터(이름, 포지션, 국적)

           이름 포지션    국적
등번호
34    그라니트 자카  MF   스위스
8    마르틴 외데고르  MF  노르웨이
5      토마스 파티  MF    가나