# 9. 데이터 선택 (조건)

조건에 해달하는 데이터 선택

In [1]:
import pandas as pd
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [5]:
df['키'] >= 180 # 선수들의 키가 180 이상인지 여부를 True/False

등번호
9     False
11     True
7     False
34     True
8     False
5      True
35    False
6      True
12     True
4      True
1      True
Name: 키, dtype: bool

In [7]:
myFilter = (df['키'] >= 180)
df[myFilter] # 필터를 만들어 조건에 참인 데이터만 가져옴

             이름 포지션    국적    키  출생년도
등번호
11   가브리엘 마르티넬리  FW   브라질  180  2001
34      그라니트 자카  MF   스위스  185  1992
5        토마스 파티  MF    가나  185  1993
6    가브리엘 마갈량이스  DF   브라질  190  1997
12      윌리엄 살리바  DF   프랑스  193  2001
4         벤 화이트  DF  잉글랜드  182  1997
1       아론 람스데일  GK  잉글랜드  188  1998

In [8]:
df[~myFilter] # 필터를 역으로 적용 (키가 180 미만인 선수들)

            이름 포지션     국적    키  출생년도
등번호
9     가브리엘 제수스  FW    브라질  175  1997
7       부카요 사카  FW   잉글랜드  178  2001
8     마르틴 외데고르  MF   노르웨이  176  1998
35   올렉산드르 진첸코  DF  우크라이나  175  1996

In [9]:
df[df['키'] >= 180] # 필터를 변수 지정 없이 사용

             이름 포지션    국적    키  출생년도
등번호
11   가브리엘 마르티넬리  FW   브라질  180  2001
34      그라니트 자카  MF   스위스  185  1992
5        토마스 파티  MF    가나  185  1993
6    가브리엘 마갈량이스  DF   브라질  190  1997
12      윌리엄 살리바  DF   프랑스  193  2001
4         벤 화이트  DF  잉글랜드  182  1997
1       아론 람스데일  GK  잉글랜드  188  1998

In [10]:
df.loc[df['키'] >= 180, '포지션'] # 키가 180 이상인 선수들의 포지션

등번호
11    FW
34    MF
5     MF
6     DF
12    DF
4     DF
1     GK
Name: 포지션, dtype: object

In [12]:
df.loc[df['키'] >= 180, ['이름', '포지션', '키']] # 키가 180 이상인 선수들의 이름, 포지션, 키

             이름 포지션    키
등번호
11   가브리엘 마르티넬리  FW  180
34      그라니트 자카  MF  185
5        토마스 파티  MF  185
6    가브리엘 마갈량이스  DF  190
12      윌리엄 살리바  DF  193
4         벤 화이트  DF  182
1       아론 람스데일  GK  188

## 다양한 조건

### & 그리고

In [14]:
df.loc[(df['키'] >= 180) & (df['포지션'] == 'MF')] # 키가 180 이상이고, 포지션이 MF인 선수 데이터

          이름 포지션   국적    키  출생년도
등번호
34   그라니트 자카  MF  스위스  185  1992
5     토마스 파티  MF   가나  185  1993

### | 또는

In [15]:
df.loc[(df['출생년도'] < 1995 )|(df['출생년도'] > 2000)] # 1995년 이전 혹은 2000년 이후에 출생한 선수 데이터

             이름 포지션    국적    키  출생년도
등번호
11   가브리엘 마르티넬리  FW   브라질  180  2001
7        부카요 사카  FW  잉글랜드  178  2001
34      그라니트 자카  MF   스위스  185  1992
5        토마스 파티  MF    가나  185  1993
12      윌리엄 살리바  DF   프랑스  193  2001

### str 함수

In [16]:
myFilter = df['이름'].str.startswith('가브리엘') # 이름이 가브리엘로 시작하는 선수
df[myFilter]

             이름 포지션   국적    키  출생년도
등번호
9      가브리엘 제수스  FW  브라질  175  1997
11   가브리엘 마르티넬리  FW  브라질  180  2001
6    가브리엘 마갈량이스  DF  브라질  190  1997

In [19]:
myFilter = df['이름'].str.contains('카') # 이름에 '카'가 들어가는 선수
df[myFilter]
# NaN 데이터는 contains 함수의 결과값이 false가 아닌 NaN
# NaN이 포함된 필터를 사용하여 일반적으로 출력을 시도하면 오류가 발생함
# contains(키워드, na=True/False)로 사용하면 NaN을 True/False로 처리할 수 있음

          이름 포지션    국적    키  출생년도
등번호
7     부카요 사카  FW  잉글랜드  178  2001
34   그라니트 자카  MF   스위스  185  1992

In [20]:
df[~myFilter] # 이름에 '카'가 들어가지 않는 선수

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [27]:
nations = ['브라질', '잉글랜드']
myFilter = df['국적'].isin(nations) # 국적이 브라질이거나 잉글랜드인 사람
df[myFilter]

             이름 포지션    국적    키  출생년도
등번호
9      가브리엘 제수스  FW   브라질  175  1997
11   가브리엘 마르티넬리  FW   브라질  180  2001
7        부카요 사카  FW  잉글랜드  178  2001
6    가브리엘 마갈량이스  DF   브라질  190  1997
4         벤 화이트  DF  잉글랜드  182  1997
1       아론 람스데일  GK  잉글랜드  188  1998