# 10. 결측치

비어 있는 데이터

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('10_ARS.xlsx', index_col='등번호')
df

             이름  포지션     국적    키  출생년도
등번호
9      가브리엘 제수스   FW    브라질  175  1997
11   가브리엘 마르티넬리   FW    브라질  180  2001
7        부카요 사카   FW   잉글랜드  178  2001
34      그라니트 자카  NaN    스위스  185  1992
8      마르틴 외데고르  NaN   노르웨이  176  1998
5        토마스 파티  NaN     가나  185  1993
35    올렉산드르 진첸코   DF  우크라이나  175  1996
6    가브리엘 마갈량이스   DF    브라질  190  1997
12      윌리엄 살리바   DF    프랑스  193  2001
4         벤 화이트   DF   잉글랜드  182  1997
1       아론 람스데일   GK   잉글랜드  188  1998

## 데이터 채우기 fillna

In [2]:
df.fillna('') # NaN 데이터를 빈 칸으로 채움

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카        스위스  185  1992
8      마르틴 외데고르       노르웨이  176  1998
5        토마스 파티         가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [3]:
df.fillna('MF') # NaN 데이터를 MF로 채움

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [5]:
df

             이름  포지션     국적    키  출생년도
등번호
9      가브리엘 제수스   FW    브라질  175  1997
11   가브리엘 마르티넬리   FW    브라질  180  2001
7        부카요 사카   FW   잉글랜드  178  2001
34      그라니트 자카  NaN    스위스  185  1992
8      마르틴 외데고르  NaN   노르웨이  176  1998
5        토마스 파티  NaN     가나  185  1993
35    올렉산드르 진첸코   DF  우크라이나  175  1996
6    가브리엘 마갈량이스   DF    브라질  190  1997
12      윌리엄 살리바   DF    프랑스  193  2001
4         벤 화이트   DF   잉글랜드  182  1997
1       아론 람스데일   GK   잉글랜드  188  1998

In [7]:
df.fillna('MF', inplace=True)

In [8]:
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [9]:
df.loc[df['포지션'] == 'MF', '포지션'] = np.nan

In [11]:
df.loc[df['국적'] == '브라질', '국적'] = np.nan

In [12]:
df

             이름  포지션     국적    키  출생년도
등번호
9      가브리엘 제수스   FW    NaN  175  1997
11   가브리엘 마르티넬리   FW    NaN  180  2001
7        부카요 사카   FW   잉글랜드  178  2001
34      그라니트 자카  NaN    스위스  185  1992
8      마르틴 외데고르  NaN   노르웨이  176  1998
5        토마스 파티  NaN     가나  185  1993
35    올렉산드르 진첸코   DF  우크라이나  175  1996
6    가브리엘 마갈량이스   DF    NaN  190  1997
12      윌리엄 살리바   DF    프랑스  193  2001
4         벤 화이트   DF   잉글랜드  182  1997
1       아론 람스데일   GK   잉글랜드  188  1998

In [17]:
df['국적'].fillna('브라질', inplace=True)

In [18]:
df

             이름  포지션     국적    키  출생년도
등번호
9      가브리엘 제수스   FW    브라질  175  1997
11   가브리엘 마르티넬리   FW    브라질  180  2001
7        부카요 사카   FW   잉글랜드  178  2001
34      그라니트 자카  NaN    스위스  185  1992
8      마르틴 외데고르  NaN   노르웨이  176  1998
5        토마스 파티  NaN     가나  185  1993
35    올렉산드르 진첸코   DF  우크라이나  175  1996
6    가브리엘 마갈량이스   DF    브라질  190  1997
12      윌리엄 살리바   DF    프랑스  193  2001
4         벤 화이트   DF   잉글랜드  182  1997
1       아론 람스데일   GK   잉글랜드  188  1998

## 데이터 제외하기 dropna

In [20]:
df.dropna() # 전체 데이터 중 NaN을 포함하는 데이터 삭제 (실제로 반영하기 위해서는 inplace 필요)

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [22]:
df = pd.read_excel('10_ARS.xlsx', index_col='등번호')
df

             이름  포지션     국적    키  출생년도
등번호
9      가브리엘 제수스   FW    브라질  175  1997
11   가브리엘 마르티넬리   FW    브라질  180  2001
7        부카요 사카   FW   잉글랜드  178  2001
34      그라니트 자카  NaN    스위스  185  1992
8      마르틴 외데고르  NaN   노르웨이  176  1998
5        토마스 파티  NaN     가나  185  1993
35    올렉산드르 진첸코   DF  우크라이나  175  1996
6    가브리엘 마갈량이스   DF    브라질  190  1997
12      윌리엄 살리바   DF    프랑스  193  2001
4         벤 화이트   DF   잉글랜드  182  1997
1       아론 람스데일   GK   잉글랜드  188  1998

- axis : index(기본값) or columns -> 행을 지울지, 열을 지울지  
- how : any(기본값) or all -> 1개라도 있을 경우, 전부 NaN일 경우

In [25]:
df.dropna(axis='index', how='any') # NaN이 하나라도 있는 row를 삭제

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [27]:
df.dropna(axis='columns') # NaN이 하나라도 있는 Column을 삭제

             이름     국적    키  출생년도
등번호
9      가브리엘 제수스    브라질  175  1997
11   가브리엘 마르티넬리    브라질  180  2001
7        부카요 사카   잉글랜드  178  2001
34      그라니트 자카    스위스  185  1992
8      마르틴 외데고르   노르웨이  176  1998
5        토마스 파티     가나  185  1993
35    올렉산드르 진첸코  우크라이나  175  1996
6    가브리엘 마갈량이스    브라질  190  1997
12      윌리엄 살리바    프랑스  193  2001
4         벤 화이트   잉글랜드  182  1997
1       아론 람스데일   잉글랜드  188  1998

In [28]:
df['국적'] = np.nan

In [29]:
df

             이름  포지션  국적    키  출생년도
등번호
9      가브리엘 제수스   FW NaN  175  1997
11   가브리엘 마르티넬리   FW NaN  180  2001
7        부카요 사카   FW NaN  178  2001
34      그라니트 자카  NaN NaN  185  1992
8      마르틴 외데고르  NaN NaN  176  1998
5        토마스 파티  NaN NaN  185  1993
35    올렉산드르 진첸코   DF NaN  175  1996
6    가브리엘 마갈량이스   DF NaN  190  1997
12      윌리엄 살리바   DF NaN  193  2001
4         벤 화이트   DF NaN  182  1997
1       아론 람스데일   GK NaN  188  1998

In [30]:
df.dropna(axis='columns', how='all') # 데이터 전체가 NaN인 '국적' Column 삭제

             이름  포지션    키  출생년도
등번호
9      가브리엘 제수스   FW  175  1997
11   가브리엘 마르티넬리   FW  180  2001
7        부카요 사카   FW  178  2001
34      그라니트 자카  NaN  185  1992
8      마르틴 외데고르  NaN  176  1998
5        토마스 파티  NaN  185  1993
35    올렉산드르 진첸코   DF  175  1996
6    가브리엘 마갈량이스   DF  190  1997
12      윌리엄 살리바   DF  193  2001
4         벤 화이트   DF  182  1997
1       아론 람스데일   GK  188  1998