# 12. 데이터 수정

In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel('12_ARS.xlsx', index_col='등번호')
df

             이름         포지션     국적    키  출생년도
등번호
9      가브리엘 제수스     Forward    브라질  175  1997
11   가브리엘 마르티넬리     Forward    브라질  180  2001
7        부카요 사카     Forward   잉글랜드  178  2001
34      그라니트 자카  Midfielder    스위스  185  1992
8      마르틴 외데고르  Midfielder   노르웨이  176  1998
5        토마스 파티  Midfielder     가나  185  1993
35    올렉산드르 진첸코    Defender  우크라이나  175  1996
6    가브리엘 마갈량이스    Defender    브라질  190  1997
12      윌리엄 살리바    Defender    프랑스  193  2001
4         벤 화이트    Defender   잉글랜드  182  1997
1       아론 람스데일  Goalkeeper   잉글랜드  188  1998

## Column 수정

In [2]:
df['포지션'].replace({'Forward':'FW', 'Midfielder':'MF', 'Defender':'DF', 'Goalkeeper':'GK'}) # 실제 데이터에 반영 시 inplace 필요

등번호
9     FW
11    FW
7     FW
34    MF
8     MF
5     MF
35    DF
6     DF
12    DF
4     DF
1     GK
Name: 포지션, dtype: object

## Column 추가

In [3]:
df['이전 소속팀'] = ['Manchester City', 'Ituano FC', np.nan, 'Borussia M\'Gladbach', 'Real Madrid CF', 'Atletico Madrid', 'Manchester City', 'Lille', 'Saint-Etienne', 'Brighton & Hove Albion', 'Sheffield United']
df

             이름         포지션     국적    키  출생년도                  이전 소속팀
등번호
9      가브리엘 제수스     Forward    브라질  175  1997         Manchester City
11   가브리엘 마르티넬리     Forward    브라질  180  2001               Ituano FC
7        부카요 사카     Forward   잉글랜드  178  2001                     NaN
34      그라니트 자카  Midfielder    스위스  185  1992     Borussia M'Gladbach
8      마르틴 외데고르  Midfielder   노르웨이  176  1998          Real Madrid CF
5        토마스 파티  Midfielder     가나  185  1993         Atletico Madrid
35    올렉산드르 진첸코    Defender  우크라이나  175  1996         Manchester City
6    가브리엘 마갈량이스    Defender    브라질  190  1997                   Lille
12      윌리엄 살리바    Defender    프랑스  193  2001           Saint-Etienne
4         벤 화이트    Defender   잉글랜드  182  1997  Brighton & Hove Albion
1       아론 람스데일  Goalkeeper   잉글랜드  188  1998        Sheffield United

In [4]:
df['홈그로운'] = 'Non-Homegrown'
df

,이름,포지션,국적,키,출생년도,이전 소속팀,홈그로운
등번호,,,,,,,
9,가브리엘 제수스,Forward,브라질,175,1997,Manchester City,Non-Homegrown
11,가브리엘 마르티넬리,Forward,브라질,180,2001,Ituano FC,Non-Homegrown
7,부카요 사카,Forward,잉글랜드,178,2001,NaN,Non-Homegrown
34,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach,Non-Homegrown
8,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF,Non-Homegrown
5,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid,Non-Homegrown
35,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City,Non-Homegrown
6,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille,Non-Homegrown
12,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne,Non-Homegrown
4,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion,Non-Homegrown
1,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United,Non-Homegrown

In [5]:
df.loc[((df['출생년도'] >= 1999) | (df['국적'] == '잉글랜드')), '홈그로운'] = 'Homegrown'
df

,이름,포지션,국적,키,출생년도,이전 소속팀,홈그로운
등번호,,,,,,,
9,가브리엘 제수스,Forward,브라질,175,1997,Manchester City,Non-Homegrown
11,가브리엘 마르티넬리,Forward,브라질,180,2001,Ituano FC,Homegrown
7,부카요 사카,Forward,잉글랜드,178,2001,NaN,Homegrown
34,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach,Non-Homegrown
8,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF,Non-Homegrown
5,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid,Non-Homegrown
35,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City,Non-Homegrown
6,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille,Non-Homegrown
12,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne,Homegrown
4,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion,Homegrown
1,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United,Homegrown

## Column 삭제

In [6]:
df.drop(columns=['이전 소속팀']) # 이전 소속팀 column 삭제 (inplace 필요)

             이름         포지션     국적    키  출생년도           홈그로운
등번호
9      가브리엘 제수스     Forward    브라질  175  1997  Non-Homegrown
11   가브리엘 마르티넬리     Forward    브라질  180  2001      Homegrown
7        부카요 사카     Forward   잉글랜드  178  2001      Homegrown
34      그라니트 자카  Midfielder    스위스  185  1992  Non-Homegrown
8      마르틴 외데고르  Midfielder   노르웨이  176  1998  Non-Homegrown
5        토마스 파티  Midfielder     가나  185  1993  Non-Homegrown
35    올렉산드르 진첸코    Defender  우크라이나  175  1996  Non-Homegrown
6    가브리엘 마갈량이스    Defender    브라질  190  1997  Non-Homegrown
12      윌리엄 살리바    Defender    프랑스  193  2001      Homegrown
4         벤 화이트    Defender   잉글랜드  182  1997      Homegrown
1       아론 람스데일  Goalkeeper   잉글랜드  188  1998      Homegrown

In [7]:
df.drop(columns=['이전 소속팀', '홈그로운']) # 이전 소속팀, 홈그로운 column 삭제

             이름         포지션     국적    키  출생년도
등번호
9      가브리엘 제수스     Forward    브라질  175  1997
11   가브리엘 마르티넬리     Forward    브라질  180  2001
7        부카요 사카     Forward   잉글랜드  178  2001
34      그라니트 자카  Midfielder    스위스  185  1992
8      마르틴 외데고르  Midfielder   노르웨이  176  1998
5        토마스 파티  Midfielder     가나  185  1993
35    올렉산드르 진첸코    Defender  우크라이나  175  1996
6    가브리엘 마갈량이스    Defender    브라질  190  1997
12      윌리엄 살리바    Defender    프랑스  193  2001
4         벤 화이트    Defender   잉글랜드  182  1997
1       아론 람스데일  Goalkeeper   잉글랜드  188  1998

## Row 삭제

In [8]:
df.drop(index=4) # 등번호(index)가 4인 선수(벤 화이트) 데이터 row 삭제

,이름,포지션,국적,키,출생년도,이전 소속팀,홈그로운
등번호,,,,,,,
9,가브리엘 제수스,Forward,브라질,175,1997,Manchester City,Non-Homegrown
11,가브리엘 마르티넬리,Forward,브라질,180,2001,Ituano FC,Homegrown
7,부카요 사카,Forward,잉글랜드,178,2001,NaN,Homegrown
34,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach,Non-Homegrown
8,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF,Non-Homegrown
5,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid,Non-Homegrown
35,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City,Non-Homegrown
6,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille,Non-Homegrown
12,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne,Homegrown
1,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United,Homegrown

In [9]:
myFilter = df['키'] < 180
df[myFilter]

            이름         포지션     국적    키  출생년도           이전 소속팀           홈그로운
등번호
9     가브리엘 제수스     Forward    브라질  175  1997  Manchester City  Non-Homegrown
7       부카요 사카     Forward   잉글랜드  178  2001              NaN      Homegrown
8     마르틴 외데고르  Midfielder   노르웨이  176  1998   Real Madrid CF  Non-Homegrown
35   올렉산드르 진첸코    Defender  우크라이나  175  1996  Manchester City  Non-Homegrown

In [10]:
df[myFilter].index

Int64Index([9, 7, 8, 35], dtype='int64', name='등번호')

In [11]:
df.drop(index=df[myFilter].index)

,이름,포지션,국적,키,출생년도,이전 소속팀,홈그로운
등번호,,,,,,,
11,가브리엘 마르티넬리,Forward,브라질,180,2001,Ituano FC,Homegrown
34,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach,Non-Homegrown
5,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid,Non-Homegrown
6,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille,Non-Homegrown
12,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne,Homegrown
4,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion,Homegrown
1,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United,Homegrown

## Row 추가

In [12]:
df.loc[11] = ['에밀 스미스로우', 'Forward', '잉글랜드', 182, 2000, np.nan, 'Homegrown'] # 새로운 row 추가
df

,이름,포지션,국적,키,출생년도,이전 소속팀,홈그로운
등번호,,,,,,,
9,가브리엘 제수스,Forward,브라질,175,1997,Manchester City,Non-Homegrown
11,에밀 스미스로우,Forward,잉글랜드,182,2000,NaN,Homegrown
7,부카요 사카,Forward,잉글랜드,178,2001,NaN,Homegrown
34,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach,Non-Homegrown
8,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF,Non-Homegrown
5,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid,Non-Homegrown
35,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City,Non-Homegrown
6,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille,Non-Homegrown
12,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne,Homegrown
4,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion,Homegrown
1,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United,Homegrown

## Cell 수정

In [13]:
df.loc[11, '포지션'] = 'Midfielder'
df

,이름,포지션,국적,키,출생년도,이전 소속팀,홈그로운
등번호,,,,,,,
9,가브리엘 제수스,Forward,브라질,175,1997,Manchester City,Non-Homegrown
11,에밀 스미스로우,Midfielder,잉글랜드,182,2000,NaN,Homegrown
7,부카요 사카,Forward,잉글랜드,178,2001,NaN,Homegrown
34,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach,Non-Homegrown
8,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF,Non-Homegrown
5,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid,Non-Homegrown
35,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City,Non-Homegrown
6,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille,Non-Homegrown
12,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne,Homegrown
4,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion,Homegrown
1,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United,Homegrown

In [14]:
df.loc[11, ['이름','포지션']] = ['에밀 스미스 로우', 'Forward']

In [15]:
df

,이름,포지션,국적,키,출생년도,이전 소속팀,홈그로운
등번호,,,,,,,
9,가브리엘 제수스,Forward,브라질,175,1997,Manchester City,Non-Homegrown
11,에밀 스미스 로우,Forward,잉글랜드,182,2000,NaN,Homegrown
7,부카요 사카,Forward,잉글랜드,178,2001,NaN,Homegrown
34,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach,Non-Homegrown
8,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF,Non-Homegrown
5,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid,Non-Homegrown
35,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City,Non-Homegrown
6,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille,Non-Homegrown
12,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne,Homegrown
4,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion,Homegrown
1,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United,Homegrown

## Column 순서 변경

In [16]:
cols = list(df.columns)
cols

['이름', '포지션', '국적', '키', '출생년도', '이전 소속팀', '홈그로운']

In [17]:
df = df[[cols[-1]] + cols[0:-1]] # 맨 뒤에 있는 홈그로운 column을 가장 앞으로 이동 / [[리스트]]의 형태
df

,홈그로운,이름,포지션,국적,키,출생년도,이전 소속팀
등번호,,,,,,,
9,Non-Homegrown,가브리엘 제수스,Forward,브라질,175,1997,Manchester City
11,Homegrown,에밀 스미스 로우,Forward,잉글랜드,182,2000,NaN
7,Homegrown,부카요 사카,Forward,잉글랜드,178,2001,NaN
34,Non-Homegrown,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach
8,Non-Homegrown,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF
5,Non-Homegrown,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid
35,Non-Homegrown,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City
6,Non-Homegrown,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille
12,Homegrown,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne
4,Homegrown,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion
1,Homegrown,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United

## Column 이름 변경

In [18]:
df

,홈그로운,이름,포지션,국적,키,출생년도,이전 소속팀
등번호,,,,,,,
9,Non-Homegrown,가브리엘 제수스,Forward,브라질,175,1997,Manchester City
11,Homegrown,에밀 스미스 로우,Forward,잉글랜드,182,2000,NaN
7,Homegrown,부카요 사카,Forward,잉글랜드,178,2001,NaN
34,Non-Homegrown,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach
8,Non-Homegrown,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF
5,Non-Homegrown,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid
35,Non-Homegrown,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City
6,Non-Homegrown,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille
12,Homegrown,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne
4,Homegrown,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion
1,Homegrown,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United

In [19]:
df.columns

Index(['홈그로운', '이름', '포지션', '국적', '키', '출생년도', '이전 소속팀'], dtype='object')

In [20]:
df.columns = ['홈그로운', '이름', '포지션', '국적', '신장', '출생년도', '이전 소속팀']
df

,홈그로운,이름,포지션,국적,신장,출생년도,이전 소속팀
등번호,,,,,,,
9,Non-Homegrown,가브리엘 제수스,Forward,브라질,175,1997,Manchester City
11,Homegrown,에밀 스미스 로우,Forward,잉글랜드,182,2000,NaN
7,Homegrown,부카요 사카,Forward,잉글랜드,178,2001,NaN
34,Non-Homegrown,그라니트 자카,Midfielder,스위스,185,1992,Borussia M'Gladbach
8,Non-Homegrown,마르틴 외데고르,Midfielder,노르웨이,176,1998,Real Madrid CF
5,Non-Homegrown,토마스 파티,Midfielder,가나,185,1993,Atletico Madrid
35,Non-Homegrown,올렉산드르 진첸코,Defender,우크라이나,175,1996,Manchester City
6,Non-Homegrown,가브리엘 마갈량이스,Defender,브라질,190,1997,Lille
12,Homegrown,윌리엄 살리바,Defender,프랑스,193,2001,Saint-Etienne
4,Homegrown,벤 화이트,Defender,잉글랜드,182,1997,Brighton & Hove Albion
1,Homegrown,아론 람스데일,Goalkeeper,잉글랜드,188,1998,Sheffield United