## 13. 함수 적용

In [1]:
import pandas as pd
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

## 데이터에 함수 적용 (apply)

In [2]:
def add_cm(height):
    return str(height) + 'cm'

df['키'] = df['키'].apply(add_cm) # 키 데이터에 대해서 add_cm 함수를 호출한 결과 데이터를 반영
df

             이름 포지션     국적      키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175cm  1997
11   가브리엘 마르티넬리  FW    브라질  180cm  2001
7        부카요 사카  FW   잉글랜드  178cm  2001
34      그라니트 자카  MF    스위스  185cm  1992
8      마르틴 외데고르  MF   노르웨이  176cm  1998
5        토마스 파티  MF     가나  185cm  1993
35    올렉산드르 진첸코  DF  우크라이나  175cm  1996
6    가브리엘 마갈량이스  DF    브라질  190cm  1997
12      윌리엄 살리바  DF    프랑스  193cm  2001
4         벤 화이트  DF   잉글랜드  182cm  1997
1       아론 람스데일  GK   잉글랜드  188cm  1998