# 14. 그룹화

동일한 값을 가진 것들끼리 합쳐서 통계 또는 평균 등의 값을 계산하기 위해 사용

In [1]:
import pandas as pd
df = pd.read_excel('04_ARS.xlsx', index_col='등번호')
df

             이름 포지션     국적    키  출생년도
등번호
9      가브리엘 제수스  FW    브라질  175  1997
11   가브리엘 마르티넬리  FW    브라질  180  2001
7        부카요 사카  FW   잉글랜드  178  2001
34      그라니트 자카  MF    스위스  185  1992
8      마르틴 외데고르  MF   노르웨이  176  1998
5        토마스 파티  MF     가나  185  1993
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997
1       아론 람스데일  GK   잉글랜드  188  1998

In [2]:
df.groupby('포지션')

In [3]:
df.groupby('포지션').get_group('FW')

             이름 포지션    국적    키  출생년도
등번호
9      가브리엘 제수스  FW   브라질  175  1997
11   가브리엘 마르티넬리  FW   브라질  180  2001
7        부카요 사카  FW  잉글랜드  178  2001

In [4]:
df.groupby('포지션').get_group('DF')

             이름 포지션     국적    키  출생년도
등번호
35    올렉산드르 진첸코  DF  우크라이나  175  1996
6    가브리엘 마갈량이스  DF    브라질  190  1997
12      윌리엄 살리바  DF    프랑스  193  2001
4         벤 화이트  DF   잉글랜드  182  1997

In [5]:
df.groupby('포지션').mean() # 계산 가능한 데이터들의 평균값

              키         출생년도
포지션
DF   185.000000  1997.750000
FW   177.666667  1999.666667
GK   188.000000  1998.000000
MF   182.000000  1994.333333

In [6]:
df.groupby('포지션').size() # 각 그룹의 크기

포지션
DF    4
FW    3
GK    1
MF    3
dtype: int64

In [7]:
df.groupby('포지션').size()['MF'] # 포지션으로 그룹화를 한 뒤에 MF에 해당하는 데이터의 수

3

In [8]:
df.groupby('포지션')['키'].mean() # 포지션으로 그룹화를 한 뒤, 키의 평균 데이터

포지션
DF    185.000000
FW    177.666667
GK    188.000000
MF    182.000000
Name: 키, dtype: float64

In [12]:
df['세부 포지션'] = ['CF', 'WF', 'WF', 'CM', 'CM', 'DM', 'FB', 'CB', 'CB', 'FB', 'GK'] # 세부 포지션 column 추가
df

             이름 포지션     국적    키  출생년도 세부 포지션
등번호
9      가브리엘 제수스  FW    브라질  175  1997     CF
11   가브리엘 마르티넬리  FW    브라질  180  2001     WF
7        부카요 사카  FW   잉글랜드  178  2001     WF
34      그라니트 자카  MF    스위스  185  1992     CM
8      마르틴 외데고르  MF   노르웨이  176  1998     CM
5        토마스 파티  MF     가나  185  1993     DM
35    올렉산드르 진첸코  DF  우크라이나  175  1996     FB
6    가브리엘 마갈량이스  DF    브라질  190  1997     CB
12      윌리엄 살리바  DF    프랑스  193  2001     CB
4         벤 화이트  DF   잉글랜드  182  1997     FB
1       아론 람스데일  GK   잉글랜드  188  1998     GK

In [13]:
df.groupby(['포지션', '세부 포지션']).mean() # 포지션별, 세부포지션별 평균 데이터

                키    출생년도
포지션 세부 포지션
DF  CB      191.5  1999.0
    FB      178.5  1996.5
FW  CF      175.0  1997.0
    WF      179.0  2001.0
GK  GK      188.0  1998.0
MF  CM      180.5  1995.0
    DM      185.0  1993.0

In [14]:
df.groupby('세부 포지션').mean() # 세부 포지션별 평균 데이터

            키    출생년도
세부 포지션
CB      191.5  1999.0
CF      175.0  1997.0
CM      180.5  1995.0
DM      185.0  1993.0
FB      178.5  1996.5
GK      188.0  1998.0
WF      179.0  2001.0

In [17]:
df.groupby('포지션').mean().sort_values('키') # 포지션별 키 오름차순 정렬

              키         출생년도
포지션
FW   177.666667  1999.666667
MF   182.000000  1994.333333
DF   185.000000  1997.750000
GK   188.000000  1998.000000

In [29]:
df.groupby('포지션')['국적'].value_counts() # 포지션으로 그룹화를 한 뒤에 각 포지션별 국적의 가짓수
"""
아래와 같은 결과
position = df.groupby('포지션')
position['국적'].value_counts()
"""

포지션  국적
DF   브라질      1
     우크라이나    1
     잉글랜드     1
     프랑스      1
FW   브라질      2
     잉글랜드     1
GK   잉글랜드     1
MF   가나       1
     노르웨이     1
     스위스      1
Name: 국적, dtype: int64

In [32]:
df.groupby('포지션')['국적'].value_counts().loc['DF'] # 포지션으로 그룹화를 한 뒤에 DF에 대한 국적 별 선수 수

국적
브라질      1
우크라이나    1
잉글랜드     1
프랑스      1
Name: 국적, dtype: int64

In [34]:
df.groupby('포지션')['국적'].value_counts(normalize=True).loc['FW'] # FW의 국적 별 퍼센트

국적
브라질     0.666667
잉글랜드    0.333333
Name: 국적, dtype: float64